wget -c http://2015.zeronights.org/assets/files/00-Branko.pdf
wget -c http://2015.zeronights.org/assets/files/01-Brown.pdf
wget -c http://2015.zeronights.org/assets/files/16-Brown.pdf
wget -c http://2015.zeronights.org/assets/files/02-Geshev.pdf
wget -c http://2015.zeronights.org/assets/files/03-Kaluzny.pdf
wget -c http://2015.zeronights.org/assets/files/04-Novikov.pdf
wget -c http://2015.zeronights.org/assets/files/05-Nosenko.pdf
wget -c http://2015.zeronights.org/assets/files/06-Zisis-Naziridis.pdf
wget -c http://2015.zeronights.org/assets/files/07-Belov.pdf
wget -c http://2015.zeronights.org/assets/files/08-Daniel-Azure.pdf
wget -c http://2015.zeronights.org/assets/files/09_Schlej.pdf
wget -c http://2015.zeronights.org/assets/files/10-Matrosov.pdf
wget -c http://2015.zeronights.org/assets/files/11-Tarakanov.pdf
wget -c http://2015.zeronights.org/assets/files/12-Krotofil.pdf
wget -c http://2015.zeronights.org/assets/files/13-Ermolov.pdf
wget -c http://2015.zeronights.org/assets/files/14-shekyan.pdf
wget -c http://2015.zeronights.org/assets/files/15-Gregorio.pdf
wget -c http://2015.zeronights.org/assets/files/17-Yunusov.pdf
wget -c http://2015.zeronights.org/assets/files/18-kochkov.pdf
wget -c http://2015.zeronights.org/assets/files/19-Plastunov.pdf
wget -c http://2015.zeronights.org/assets/files/20-Litvinov.pdf
wget -c http://2015.zeronights.org/assets/files/21-Beccaro-Collura%20.pdf
wget -c http://2015.zeronights.org/assets/files/23-Ravnas.pdf
wget -c http://2015.zeronights.org/assets/files/42-Elkin-Bulatenko.pdf
wget -c http://2015.zeronights.org/assets/files/43-bolshev-ryutin.pdf
wget -c http://2015.zeronights.org/assets/files/40-ValdikSS.pdf
wget -c http://2015.zeronights.org/assets/files/32-Firstov.pdf
wget -c http://2015.zeronights.org/assets/files/33-Matrosov-Rodionov.pdf
wget -c http://2015.zeronights.org/assets/files/34-Kolegov.pdf
wget -c http://2015.zeronights.org/assets/files/36-Egorov-Soldatov.pdf
wget -c http://2015.zeronights.org/assets/files/35-Egorov.pdf
wget -c http://2015.zeronights.org/assets/files/37-Ignatov.pdf
wget -c http://2015.zeronights.org/assets/files/25-Klendar.pdf
wget -c http://2015.zeronights.org/assets/files/26-svetlov.pdf
wget -c http://2015.zeronights.org/assets/files/27-Kovalev.pdf
wget -c http://2015.zeronights.org/assets/files/28-Levin.pdf
wget -c http://2015.zeronights.org/assets/files/29-Zaitov.pdf
wget -c http://2015.zeronights.org/assets/files/30-Shabalin.pdf
wget -c http://2015.zeronights.org/assets/files/31-Ermakov.pdf
wget -c http://2015.zeronights.org/assets/files/41-ructfe.pdf
